services:
  - type: web
    name: flask-app
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y ffmpeg
      pip install -r requirements.txt
      mkdir -p downloads
    startCommand: |
      gunicorn app:app \
        --timeout 300 \
        --workers 2 \
        --threads 2 \
        --worker-class gthread \
        --worker-tmp-dir /dev/shm \
        --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: YT_DLP_OPTIONS
        value: "--no-check-certificate --format best"
    routes:
      - type: route
        name: flask-app-route
        path: "/"
